const express = require('express')
const dotenv = require('dotenv')
const connectDB = require('./config/db')
const { startPolling } = require('./controllers/sqsqueuing')
const runRoute = require('./routes/runRoute')
dotenv.config()
const app = express()
app.use(express.json())
app.use((req, res, next) => {
  console.log(`[${req.method}] ${req.originalUrl}`)
  next()
})
app.use('/api', runRoute)
connectDB()
startPolling()
const PORT = process.env.PORT
app.listen(PORT, () => console.log(`Server running on port ${PORT}`))
